Repository thomasbnt/Bord-Pi, pull requests merged in 2019-10, with the labels that each got.

#21 Ajouter plus d'espace dans chaque ligne pour une meilleure lecture et mettre à jour une partie
  commands/avatar.js
  commands/bord.js
  commands/emmita.js
  commands/emmitr.js
  commands/form.js
  commands/jeu.js
  commands/kimiwa.js
  commands/markdown.js
  commands/mrrobot.js
  commands/ping.js
  commands/reddit.js
  commands/sd.js
  commands/support.js
  commands/uptime.js
  commands/whcolors.js
  events/guildMemberAdd.js
  events/guildMemberRemove.js
  events/message.js
  events/ready.js
Labels: Hacktoberfest

#23 Modification du système du chargement de commande pour trier les commandes par catégories
  README.md
  app.js
  commands/Info/form.js
  commands/Info/reddit.js
  commands/Info/support.js
  commands/Info/uptime.js
  commands/Miscellaneous/avatar.js
  commands/Miscellaneous/bord.js
  commands/Miscellaneous/markdown.js
  commands/Miscellaneous/ping.js
  commands/Miscellaneous/roll.js
  commands/Miscellaneous/sd.js
  commands/Test/emmita.js
  commands/Test/emmitr.js
  commands/Test/whcolors.js
  commands/addRole/jeu.js
  commands/addRole/kimiwa.js
  commands/addRole/mrrobot.js
  package-lock.json
  package.json
Labels: Hacktoberfest, Nouvelle demande

#25 Ajout du Feed RSS pour Subreddit
  app.js
  config.exemple.json
  events/ready.js
  package-lock.json
  package.json
Labels: Nouvelle demande
